version: '3.8'

services:
 storage:
  image: redis:latest
  volumes:
   - ./data:/data

 counter:
  build: ./book-counter
  ports:
   - 80:3002
  environment:
   - PORT=3002
   - STORAGE_URL=storage
  depends_on:
   - storage

 books:
  build: ./book-main
  ports:
   - 3000:3000
  environment:
   - PORT=3000
  depends_on:
   - counter
   - mongo

 mongo:
  image: mongo
  restart: always
  ports:
   - 27017:27017
  environment:
   - MONGO_INITDB_DATABASE=db

 mongo-express:
  image: mongo-express
  restart: always
  ports:
   - 8081:8081
  environment:
   ME_CONFIG_MONGODB_ADMINUSERNAME: root
   ME_CONFIG_MONGODB_ADMINPASSWORD: example
  depends_on:
   - mongo